In [1]:
import pandas as pd
import sqlalchemy
import pyarrow as pa

In [2]:
import pyarrow as pa
print(pa.__version__)

24.0.0

## Cleaning

In [3]:
## AAPL
AAPL=pd.read_csv(r'D:\Ahmed\Data engineering - MSC\Stock-Market-Data-Pipeline-Analysis\dags\raw_data\AAPL.csv')
AAPL.head()

         Date      Close       High        Low       Open     Volume
0  2020-01-02  72.400513  72.460776  71.156674  71.409778  135480400
1  2020-01-03  71.696640  72.455958  71.472462  71.629145  146322800
2  2020-01-06  72.267929  72.306499  70.568503  70.819201  118387200
3  2020-01-07  71.928055  72.533095  71.708695  72.277578  108872000
4  2020-01-08  73.085091  73.386408  71.631537  71.631537  132079200

In [4]:
AAPL.tail()

            Date       Close        High         Low        Open    Volume
1587  2026-04-28  270.709991  273.230011  268.660004  272.339996  40018900
1588  2026-04-29  270.170013  271.040009  267.040009  267.549988  30047900
1589  2026-04-30  271.350006  276.000000  268.140015  270.500000  91848200
1590  2026-05-01  280.140015  287.220001  278.369995  278.859985  79844600
1591  2026-05-04  276.829987  280.630005  274.860107  279.654999  45414226

In [5]:
AAPL.info()

<class 'pandas.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1592 non-null   str
 1   Close   1592 non-null   float64
 2   High    1592 non-null   float64
 3   Low     1592 non-null   float64
 4   Open    1592 non-null   float64
 5   Volume  1592 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 90.3 KB

In [6]:
AAPL['Date']=pd.to_datetime(AAPL['Date'])
AAPL['Date']=AAPL['Date'].astype(pd.ArrowDtype(pa.date64()))
AAPL.info()

<class 'pandas.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1592 non-null   date64[ms][pyarrow]
 1   Close   1592 non-null   float64
 2   High    1592 non-null   float64
 3   Low     1592 non-null   float64
 4   Open    1592 non-null   float64
 5   Volume  1592 non-null   int64
dtypes: date64[ms][pyarrow](1), float64(4), int64(1)
memory usage: 74.8 KB

In [7]:
aapl=AAPL.duplicated(keep=False).sum() #---->> noo duplicates
aapl

np.int64(0)

In [8]:
Numeric=AAPL.drop(columns=['Date'])
                                          #there's no  negative values in the numric data (prices,volums)
eg_count=(Numeric <= 0).sum()              
print('Nagtiive values :',eg_count)

Nagtiive values : Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [9]:
AAPL.isnull().sum() # there is no missing values

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [10]:
AMD=pd.read_csv(r'D:\Ahmed\Data engineering - MSC\Stock-Market-Data-Pipeline-Analysis\dags\raw_data\AMD.csv')
AMD.head()

         Date      Close       High        Low       Open    Volume
0  2020-01-02  49.099998  49.250000  46.630001  46.860001  80331100
1  2020-01-03  48.599998  49.389999  47.540001  48.029999  73127400
2  2020-01-06  48.389999  48.860001  47.860001  48.020000  47934900
3  2020-01-07  48.250000  49.389999  48.040001  49.349998  58061400
4  2020-01-08  47.830002  48.299999  47.139999  47.849998  53767000

In [11]:
AMD.info()

<class 'pandas.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1592 non-null   str
 1   Close   1592 non-null   float64
 2   High    1592 non-null   float64
 3   Low     1592 non-null   float64
 4   Open    1592 non-null   float64
 5   Volume  1592 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 90.3 KB

In [12]:
AMD['Date']=pd.to_datetime(AMD['Date']).astype(pd.ArrowDtype(pa.date64()))

In [13]:
amd=AMD.duplicated(keep=False).sum() #---->> noo duplicates
print(amd)

0

In [14]:
Numeric=AAPL.drop(columns=['Date'])
                                          #there's no  negative values in the numric data (prices,volums)
eg_count=(Numeric <= 0).sum()              
print('Nagtiive values :',eg_count)

Nagtiive values : Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [15]:
AMD.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [16]:
AMZN=pd.read_csv(r'D:\Ahmed\Data engineering - MSC\Stock-Market-Data-Pipeline-Analysis\dags\raw_data\AMZN.csv')
AMZN.head()

         Date      Close       High        Low       Open    Volume
0  2020-01-02  94.900497  94.900497  93.207497  93.750000  80580000
1  2020-01-03  93.748497  94.309998  93.224998  93.224998  75288000
2  2020-01-06  95.143997  95.184502  93.000000  93.000000  81236000
3  2020-01-07  95.343002  95.694504  94.601997  95.224998  80898000
4  2020-01-08  94.598503  95.550003  94.321999  94.902000  70160000

In [17]:
AMZN.info()

<class 'pandas.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1592 non-null   str
 1   Close   1592 non-null   float64
 2   High    1592 non-null   float64
 3   Low     1592 non-null   float64
 4   Open    1592 non-null   float64
 5   Volume  1592 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 90.3 KB

In [18]:
AMZN['Date']=pd.to_datetime(AMZN['Date']).astype(pd.ArrowDtype(pa.date64()))

In [19]:
amd=AMZN.duplicated(keep=False).sum() #---->> noo duplicates
print(amd)

0

In [20]:
Numeric=AMZN.drop(columns=['Date'])  #there's no  negative values in the numric data (prices,volums)
eg_count=(Numeric <= 0).sum()              
print('Nagtiive values :',eg_count)

Nagtiive values : Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [21]:
AMZN.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [22]:
from pathlib import Path

RAW_DATA = Path(r"D:\Ahmed\Data engineering - MSC\Stock-Market-Data-Pipeline-Analysis\dags\raw_data")
date_dtype = pd.ArrowDtype(pa.date64())

stock_dfs = {}
for csv_path in sorted(RAW_DATA.glob("*.csv")):
    ticker = csv_path.stem
    df = pd.read_csv(csv_path)
    df["Date"] = pd.to_datetime(df["Date"]).astype(date_dtype)

    dup = df.duplicated(keep=False).sum()
    numeric = df.drop(columns=["Date"])
    neg_count = (numeric <= 0).sum()
    null_count = df.isnull().sum()

    stock_dfs[ticker] = df
    print(f"=== {ticker} ===")
    print(f"  rows={len(df)}, duplicates={dup}")
    print(f"  nulls:", null_count.to_dict())
    print(f"  <=0 counts:", neg_count.to_dict())
    print()

=== AAPL ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== AMD ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== AMZN ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== GOOGL ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== META ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== MSFT ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== NFLX ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== NVDA ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== TEAM ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

=== TSLA ===
  rows=1592, duplicates=0
  nulls: {'Date': 0, 'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}
  <=0 counts: {'Close': 0, 'High': 0, 'Low': 0, 'Open': 0, 'Volume': 0}

In [23]:
GOOGL = stock_dfs["GOOGL"]
META = stock_dfs["META"]
MSFT = stock_dfs["MSFT"]
NFLX = stock_dfs["NFLX"]
NVDA = stock_dfs["NVDA"]
TEAM = stock_dfs["TEAM"]
TSLA = stock_dfs["TSLA"]
AAPL = stock_dfs["AAPL"]
AMD = stock_dfs["AMD"]
AMZN = stock_dfs["AMZN"]

sorted(stock_dfs.keys())

['AAPL',
 'AMD',
 'AMZN',
 'GOOGL',
 'META',
 'MSFT',
 'NFLX',
 'NVDA',
 'TEAM',
 'TSLA']

## Transformation

In [24]:

for ticker, df in stock_dfs.items():
    df['pct_change']    = df['Close'].pct_change() * 100
    df['price_range']   = df['High'] - df['Low']
    df['Moving_Average']          = df['Close'].rolling(window=7).mean() 
    df['daily_return']  = df['Close'].pct_change()
    df['volatility']  = df['daily_return'].rolling(window=7).std()
    
    df.fillna(0,inplace=True)
    stock_dfs[ticker] = df  # save changes back

In [25]:
dfs = []
for ticker, df in stock_dfs.items():
    df['ticker'] = ticker    # add ticker column from the dictionary key
    dfs.append(df)

# Combine all into ONE table
fact_stock_prices = pd.concat(dfs, ignore_index=True)
print(fact_stock_prices.head())
print(fact_stock_prices['ticker'].unique())  # verify all tickers are there

         Date      Close       High        Low       Open     Volume  \
0  2020-01-02  72.400513  72.460776  71.156674  71.409778  135480400
1  2020-01-03  71.696640  72.455958  71.472462  71.629145  146322800
2  2020-01-06  72.267929  72.306499  70.568503  70.819201  118387200
3  2020-01-07  71.928055  72.533095  71.708695  72.277578  108872000
4  2020-01-08  73.085091  73.386408  71.631537  71.631537  132079200

   pct_change  price_range  Moving_Average  daily_return  volatility ticker
0    0.000000     1.304102             0.0      0.000000         0.0   AAPL
1   -0.972193     0.983496             0.0     -0.009722         0.0   AAPL
2    0.796814     1.737996             0.0      0.007968         0.0   AAPL
3   -0.470298     0.824400             0.0     -0.004703         0.0   AAPL
4    1.608602     1.754871             0.0      0.016086         0.0   AAPL
<ArrowStringArray>
['AAPL', 'AMD', 'AMZN', 'GOOGL', 'META', 'MSFT', 'NFLX', 'NVDA', 'TEAM',
 'TSLA']
Length: 10, dtype: str

In [32]:
# Fix the date column
fact_stock_prices['date'] = pd.to_datetime(fact_stock_prices['date'])

# Verify it changed
print(fact_stock_prices.dtypes)

date              datetime64[s]
close                   float64
high                    float64
low                     float64
open                    float64
volume                    int64
pct_change              float64
price_range             float64
moving_average          float64
daily_return            float64
volatility              float64
ticker                      str
dtype: object

In [33]:
fact_stock_prices = fact_stock_prices.rename(columns={
    'Date'   : 'date',
    'Open'   : 'open',
    'High'   : 'high',
    'Low'    : 'low',
    'Close'  : 'close',
    'Volume' : 'volume',
    'Moving_Average':'moving_average',
    
})

In [34]:
fact_stock_prices.head()

,date,close,high,low,open,volume,pct_change,price_range,moving_average,daily_return,volatility,ticker
0,2020-01-02,72.400513,72.460776,71.156674,71.409778,135480400,0.000000,1.304102,0.0,0.000000,0.0,AAPL
1,2020-01-03,71.696640,72.455958,71.472462,71.629145,146322800,-0.972193,0.983496,0.0,-0.009722,0.0,AAPL
2,2020-01-06,72.267929,72.306499,70.568503,70.819201,118387200,0.796814,1.737996,0.0,0.007968,0.0,AAPL
3,2020-01-07,71.928055,72.533095,71.708695,72.277578,108872000,-0.470298,0.824400,0.0,-0.004703,0.0,AAPL
4,2020-01-08,73.085091,73.386408,71.631537,71.631537,132079200,1.608602,1.754871,0.0,0.016086,0.0,AAPL

In [35]:
fact_stock_prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 15920 entries, 0 to 15919
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            15920 non-null  datetime64[s]
 1   close           15920 non-null  float64
 2   high            15920 non-null  float64
 3   low             15920 non-null  float64
 4   open            15920 non-null  float64
 5   volume          15920 non-null  int64
 6   pct_change      15920 non-null  float64
 7   price_range     15920 non-null  float64
 8   moving_average  15920 non-null  float64
 9   daily_return    15920 non-null  float64
 10  volatility      15920 non-null  float64
 11  ticker          15920 non-null  str
dtypes: datetime64[s](1), float64(9), int64(1), str(1)
memory usage: 1.5 MB

## Loading

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:postgres123@localhost:5433/stock"
)

with engine.begin() as conn:
    
    fact_stock_prices.to_sql(
        "fact_stock_prices",
        conn,
        if_exists="append",
        index=False,
    )